### ISSUE TITLE
识别结果: 利好很高性任十米

### ISSUE THREAD

**Issue by linzehua** [lukhy/masr#1]

**Comment by lukhy** [comment]
目前效果是这样的，毕竟只有150h的训练数据。
你可以用这段语音去测试下Github上其他的同类项目[手动狗头]。
外接语言模型可以把这句话识别到全对，但会麻烦一些。等我过两天把代码push上来，欢迎再次测试。

**Comment by linzehua** [comment]
> 目前效果是这样的，毕竟只有150h的训练数据。
> 你可以用这段语音去测试下Github上其他的同类项目[手动狗头]。
> 外接语言模型可以把这句话识别到全对，但会麻烦一些。等我过两天把代码push上来，欢迎再次测试。

没事没事，我只是陈述一下，我觉得你的这个很有意义，加油

另外，如果通过识别拼音再转成汉字会不会好点？

**Comment by linzehua** [comment]
另外，我知道有中文的语言模型，也许会有帮助
https://github.com/PaddlePaddle/DeepSpeech#released-models

**Comment by lukhy** [comment]
谢谢。
刚刚更新了项目，已经加入了语言模型的支持，参见[使用语言模型提升识别率](https://github.com/lukhy/masr#使用语言模型提升识别率)

> 另外，我知道有中文的语言模型，也许会有帮助
> https://github.com/PaddlePaddle/DeepSpeech#released-models

我借用的正是百度的剪枝版语言模型。
在都不使用语言模型的情况下，MASR的效果和百度的DeepSpeech使用AISHELL-1训练的效果差不多。
我在[对比](https://github.com/lukhy/masr/blob/master/docs/compare.md)中将二者进行过对比。
加入语言模型后真的有质的飞跃，我和实验室的同学都觉得很惊喜的。推荐你试试。「你好很高兴认识你」反正是一个字都没错啦。

> 另外，如果通过识别拼音再转成汉字会不会好点？

[这个项目](https://github.com/nl8590687/ASRT_SpeechRecognition)使用的就是「语音 -> 拼音 -> 汉字」的方式，语言模型接受拼音作为输入。但是整体效果不如MASR配合百度的语言模型，和不使用语言模型的MASR差不多。当然这么比较是不公平的，它用来训练声学模型的数据集虽然比MASR要大几倍（500h vs 150h），但我不知道它的语言模型是从什么语料库里训练的，但可以肯定的是没法和百度的内部语料库相比。

这个想法究竟有没有效果，还有待实验。但是似乎没有太多人对这个有兴趣。工业界不缺训练数据，实践中直接输出文字效果很好，它们自然没兴趣关注小数据集下有没有提升性能的办法；学术界还是拿英语做实验的居多，而其实英语的开放语料库也够大了，光Librispeech就有1000h。
