### ISSUE TITLE
预训练模型百度网盘失效了，可以再提供一份吗，谢谢~

### ISSUE THREAD

**Issue by YasinZhao** [lukhy/masr#20]
rt~

**Comment by YasinZhao** [comment]
已重新提供，谢谢~

**Comment by JovanLiu** [comment]
想請問...
预训练模型和测试音频文件...
還是無法下載!
能再提供一份嗎..

**Comment by YasinZhao** [comment]
作者的百度网盘分享是可以访问的啊，或者你给我个邮箱吧，我发给你~

**Comment by JovanLiu** [comment]
> 作者的百度网盘分享是可以访问的啊，或者你给我个邮箱吧，我发给你~

arnk520@gmail.com

謝謝您~~

**Comment by YasinZhao** [comment]
> > 作者的百度网盘分享是可以访问的啊，或者你给我个邮箱吧，我发给你~
> 
> [arnk520@gmail.com](mailto:arnk520@gmail.com)
> 
> 謝謝您~

已经发送了，你注意查收一下~

**Comment by davidswei** [comment]
> 作者的百度网盘分享是可以访问的啊，或者你给我个邮箱吧，我发给你~

能发给我一份吗？谢谢！sw@cust.edu.cn

**Comment by wbj0110** [comment]
@YasinZhao 能发我一份吗，谢谢1337560703@qq.com
