### ISSUE TITLE
Mac安装ctc解码包时出现这个问题

### ISSUE THREAD

**Issue by gs5264** [lukhy/masr#25]
sudo pip install .
WARNING: The directory '/Users/gongshuai/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/Users/gongshuai/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /Users/gongshuai/Desktop/masr/masr/ctcdecode
Building wheels for collected packages: ctcdecode
  Building wheel for ctcdecode (setup.py) ... error
  ERROR: Complete output from command /anaconda3/envs/masr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-req-build-59y8nu38/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/tmp/pip-wheel-99e1qp11 --python-tag cp36:
  ERROR: No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
  /anaconda3/envs/masr/lib/python3.6/distutils/extension.py:131: UserWarning: Unknown Extension options: 'package', 'with_cuda'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/ctcdecode
  copying ctcdecode/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/ctcdecode
  running build_ext
  /anaconda3/envs/masr/lib/python3.6/site-packages/torch/utils/cpp_extension.py:166: UserWarning:
  
                                 !! WARNING !!
  
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Your compiler (g++) is not compatible with the compiler Pytorch was
  built with for this platform, which is clang++ on darwin. Please
  use clang++ to to compile your extension. Alternatively, you may
  compile PyTorch from source using g++, and then you can also use
  g++ to compile your extension.
  
  See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
  with compiling PyTorch from source.
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  
                                !! WARNING !!
  
    platform=sys.platform))
  building 'ctcdecode._ext.ctc_decode' extension
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/ctcdecode
  creating build/temp.macosx-10.7-x86_64-3.6/ctcdecode/src
  creating build/temp.macosx-10.7-x86_64-3.6/third_party
  creating build/temp.macosx-10.7-x86_64-3.6/third_party/kenlm
  creating build/temp.macosx-10.7-x86_64-3.6/third_party/kenlm/util
  creating build/temp.macosx-10.7-x86_64-3.6/third_party/kenlm/lm
  creating build/temp.macosx-10.7-x86_64-3.6/third_party/kenlm/util/double-conversion
  creating build/temp.macosx-10.7-x86_64-3.6/third_party/openfst-1.6.7
  creating build/temp.macosx-10.7-x86_64-3.6/third_party/openfst-1.6.7/src
  creating build/temp.macosx-10.7-x86_64-3.6/third_party/openfst-1.6.7/src/lib
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/envs/masr/include -arch x86_64 -I/anaconda3/envs/masr/include -arch x86_64 -I/private/tmp/pip-req-build-59y8nu38/third_party/kenlm -I/private/tmp/pip-req-build-59y8nu38/third_party/openfst-1.6.7/src/include -I/private/tmp/pip-req-build-59y8nu38/third_party/ThreadPool -I/private/tmp/pip-req-build-59y8nu38/third_party/boost_1_67_0 -I/private/tmp/pip-req-build-59y8nu38/third_party/utf8 -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/include/python3.6m -c ctcdecode/src/path_trie.cpp -o build/temp.macosx-10.7-x86_64-3.6/ctcdecode/src/path_trie.o -O3 -DKENLM_MAX_ORDER=6 -std=c++11 -fPIC -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB -DINCLUDE_KENLM -DKENLM_MAX_ORDER=6 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ctc_decode -D_GLIBCXX_USE_CXX11_ABI=0
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/envs/masr/include -arch x86_64 -I/anaconda3/envs/masr/include -arch x86_64 -I/private/tmp/pip-req-build-59y8nu38/third_party/kenlm -I/private/tmp/pip-req-build-59y8nu38/third_party/openfst-1.6.7/src/include -I/private/tmp/pip-req-build-59y8nu38/third_party/ThreadPool -I/private/tmp/pip-req-build-59y8nu38/third_party/boost_1_67_0 -I/private/tmp/pip-req-build-59y8nu38/third_party/utf8 -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/include/python3.6m -c ctcdecode/src/binding.cpp -o build/temp.macosx-10.7-x86_64-3.6/ctcdecode/src/binding.o -O3 -DKENLM_MAX_ORDER=6 -std=c++11 -fPIC -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB -DINCLUDE_KENLM -DKENLM_MAX_ORDER=6 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ctc_decode -D_GLIBCXX_USE_CXX11_ABI=0
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/envs/masr/include -arch x86_64 -I/anaconda3/envs/masr/include -arch x86_64 -I/private/tmp/pip-req-build-59y8nu38/third_party/kenlm -I/private/tmp/pip-req-build-59y8nu38/third_party/openfst-1.6.7/src/include -I/private/tmp/pip-req-build-59y8nu38/third_party/ThreadPool -I/private/tmp/pip-req-build-59y8nu38/third_party/boost_1_67_0 -I/private/tmp/pip-req-build-59y8nu38/third_party/utf8 -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/include/python3.6m -c ctcdecode/src/decoder_utils.cpp -o build/temp.macosx-10.7-x86_64-3.6/ctcdecode/src/decoder_utils.o -O3 -DKENLM_MAX_ORDER=6 -std=c++11 -fPIC -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB -DINCLUDE_KENLM -DKENLM_MAX_ORDER=6 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ctc_decode -D_GLIBCXX_USE_CXX11_ABI=0
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/envs/masr/include -arch x86_64 -I/anaconda3/envs/masr/include -arch x86_64 -I/private/tmp/pip-req-build-59y8nu38/third_party/kenlm -I/private/tmp/pip-req-build-59y8nu38/third_party/openfst-1.6.7/src/include -I/private/tmp/pip-req-build-59y8nu38/third_party/ThreadPool -I/private/tmp/pip-req-build-59y8nu38/third_party/boost_1_67_0 -I/private/tmp/pip-req-build-59y8nu38/third_party/utf8 -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/include/python3.6m -c ctcdecode/src/scorer.cpp -o build/temp.macosx-10.7-x86_64-3.6/ctcdecode/src/scorer.o -O3 -DKENLM_MAX_ORDER=6 -std=c++11 -fPIC -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB -DINCLUDE_KENLM -DKENLM_MAX_ORDER=6 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ctc_decode -D_GLIBCXX_USE_CXX11_ABI=0
  warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  ctcdecode/src/binding.cppIn file included from ctcdecode/src/decoder_utils.cpp:1In file included from ctcdecode/src/path_trie.cpp::10:: fatal error11:
  : ctcdecode/src/decoder_utils.h:
  ctcdecode/src/path_trie.h'algorithm' file not found::
  4:104: fatal error: 'utility' file not found:
  10: fatal error: 'algorithm' file not found
  In file included from ctcdecode/src/scorer.cpp:1:
  ctcdecode/src/scorer.h:4:10: fatal error: 'memory' file not found
  #include <memory>
  #include <algorithm>
           ^~~~~~~~~~~
           ^~~~~~~~
  #include <utility>
  #include <algorithm>
           ^~~~~~~~~~~
           ^~~~~~~~~
  1 warning and 1 error generated.
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/envs/masr/include -arch x86_64 -I/anaconda3/envs/masr/include -arch x86_64 -I/private/tmp/pip-req-build-59y8nu38/third_party/kenlm -I/private/tmp/pip-req-build-59y8nu38/third_party/openfst-1.6.7/src/include -I/private/tmp/pip-req-build-59y8nu38/third_party/ThreadPool -I/private/tmp/pip-req-build-59y8nu38/third_party/boost_1_67_0 -I/private/tmp/pip-req-build-59y8nu38/third_party/utf8 -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/include/python3.6m -c ctcdecode/src/ctc_beam_search_decoder.cpp -o build/temp.macosx-10.7-x86_64-3.6/ctcdecode/src/ctc_beam_search_decoder.o -O3 -DKENLM_MAX_ORDER=6 -std=c++11 -fPIC -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB -DINCLUDE_KENLM -DKENLM_MAX_ORDER=6 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ctc_decode -D_GLIBCXX_USE_CXX11_ABI=0
  1 warning and 1 error generated.
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/envs/masr/include -arch x86_64 -I/anaconda3/envs/masr/include -arch x86_64 -I/private/tmp/pip-req-build-59y8nu38/third_party/kenlm -I/private/tmp/pip-req-build-59y8nu38/third_party/openfst-1.6.7/src/include -I/private/tmp/pip-req-build-59y8nu38/third_party/ThreadPool -I/private/tmp/pip-req-build-59y8nu38/third_party/boost_1_67_0 -I/private/tmp/pip-req-build-59y8nu38/third_party/utf8 -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/include/python3.6m -c third_party/kenlm/util/pool.cc -o build/temp.macosx-10.7-x86_64-3.6/third_party/kenlm/util/pool.o -O3 -DKENLM_MAX_ORDER=6 -std=c++11 -fPIC -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB -DINCLUDE_KENLM -DKENLM_MAX_ORDER=6 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ctc_decode -D_GLIBCXX_USE_CXX11_ABI=0
  error: command 'gcc' failed with exit status 1
  warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  In file included from ctcdecode/src/ctc_beam_search_decoder.cpp:1:
  ctcdecode/src/ctc_beam_search_decoder.h:4:10: fatal error: 'string' file not found
  #include <string>
           ^~~~~~~~
  warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  In file included from third_party/kenlm/util/pool.cc:1:
  /private/tmp/pip-req-build-59y8nu38/third_party/kenlm/util/pool.hh:4:10: fatal error: 'cassert' file not found
  #include <cassert>
           ^~~~~~~~~
  1 warning and 1 error generated.
  1 warning and 1 error generated.
  1 warning and 1 error generated.
  1 warning and 1 error generated.
  ----------------------------------------
  ERROR: Failed building wheel for ctcdecode
  Running setup.py clean for ctcdecode
Failed to build ctcdecode
Installing collected packages: ctcdecode
  Running setup.py install for ctcdecode ... error
    ERROR: Complete output from command /anaconda3/envs/masr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-req-build-59y8nu38/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-7w9xl5so/install-record.txt --single-version-externally-managed --compile:
    ERROR: No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    /anaconda3/envs/masr/lib/python3.6/distutils/extension.py:131: UserWarning: Unknown Extension options: 'package', 'with_cuda'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/ctcdecode
    copying ctcdecode/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/ctcdecode
    running build_ext
    /anaconda3/envs/masr/lib/python3.6/site-packages/torch/utils/cpp_extension.py:166: UserWarning:
    
                                   !! WARNING !!
    
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    Your compiler (g++) is not compatible with the compiler Pytorch was
    built with for this platform, which is clang++ on darwin. Please
    use clang++ to to compile your extension. Alternatively, you may
    compile PyTorch from source using g++, and then you can also use
    g++ to compile your extension.
    
    See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
    with compiling PyTorch from source.
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    
                                  !! WARNING !!
    
      platform=sys.platform))
    building 'ctcdecode._ext.ctc_decode' extension
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/ctcdecode
    creating build/temp.macosx-10.7-x86_64-3.6/ctcdecode/src
    creating build/temp.macosx-10.7-x86_64-3.6/third_party
    creating build/temp.macosx-10.7-x86_64-3.6/third_party/kenlm
    creating build/temp.macosx-10.7-x86_64-3.6/third_party/kenlm/util
    creating build/temp.macosx-10.7-x86_64-3.6/third_party/kenlm/lm
    creating build/temp.macosx-10.7-x86_64-3.6/third_party/kenlm/util/double-conversion
    creating build/temp.macosx-10.7-x86_64-3.6/third_party/openfst-1.6.7
    creating build/temp.macosx-10.7-x86_64-3.6/third_party/openfst-1.6.7/src
    creating build/temp.macosx-10.7-x86_64-3.6/third_party/openfst-1.6.7/src/lib
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/envs/masr/include -arch x86_64 -I/anaconda3/envs/masr/include -arch x86_64 -I/private/tmp/pip-req-build-59y8nu38/third_party/kenlm -I/private/tmp/pip-req-build-59y8nu38/third_party/openfst-1.6.7/src/include -I/private/tmp/pip-req-build-59y8nu38/third_party/ThreadPool -I/private/tmp/pip-req-build-59y8nu38/third_party/boost_1_67_0 -I/private/tmp/pip-req-build-59y8nu38/third_party/utf8 -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/include/python3.6m -c ctcdecode/src/path_trie.cpp -o build/temp.macosx-10.7-x86_64-3.6/ctcdecode/src/path_trie.o -O3 -DKENLM_MAX_ORDER=6 -std=c++11 -fPIC -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB -DINCLUDE_KENLM -DKENLM_MAX_ORDER=6 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ctc_decode -D_GLIBCXX_USE_CXX11_ABI=0
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/envs/masr/include -arch x86_64 -I/anaconda3/envs/masr/include -arch x86_64 -I/private/tmp/pip-req-build-59y8nu38/third_party/kenlm -I/private/tmp/pip-req-build-59y8nu38/third_party/openfst-1.6.7/src/include -I/private/tmp/pip-req-build-59y8nu38/third_party/ThreadPool -I/private/tmp/pip-req-build-59y8nu38/third_party/boost_1_67_0 -I/private/tmp/pip-req-build-59y8nu38/third_party/utf8 -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/include/python3.6m -c ctcdecode/src/binding.cpp -o build/temp.macosx-10.7-x86_64-3.6/ctcdecode/src/binding.o -O3 -DKENLM_MAX_ORDER=6 -std=c++11 -fPIC -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB -DINCLUDE_KENLM -DKENLM_MAX_ORDER=6 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ctc_decode -D_GLIBCXX_USE_CXX11_ABI=0
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/envs/masr/include -arch x86_64 -I/anaconda3/envs/masr/include -arch x86_64 -I/private/tmp/pip-req-build-59y8nu38/third_party/kenlm -I/private/tmp/pip-req-build-59y8nu38/third_party/openfst-1.6.7/src/include -I/private/tmp/pip-req-build-59y8nu38/third_party/ThreadPool -I/private/tmp/pip-req-build-59y8nu38/third_party/boost_1_67_0 -I/private/tmp/pip-req-build-59y8nu38/third_party/utf8 -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/include/python3.6m -c ctcdecode/src/decoder_utils.cpp -o build/temp.macosx-10.7-x86_64-3.6/ctcdecode/src/decoder_utils.o -O3 -DKENLM_MAX_ORDER=6 -std=c++11 -fPIC -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB -DINCLUDE_KENLM -DKENLM_MAX_ORDER=6 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ctc_decode -D_GLIBCXX_USE_CXX11_ABI=0
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/envs/masr/include -arch x86_64 -I/anaconda3/envs/masr/include -arch x86_64 -I/private/tmp/pip-req-build-59y8nu38/third_party/kenlm -I/private/tmp/pip-req-build-59y8nu38/third_party/openfst-1.6.7/src/include -I/private/tmp/pip-req-build-59y8nu38/third_party/ThreadPool -I/private/tmp/pip-req-build-59y8nu38/third_party/boost_1_67_0 -I/private/tmp/pip-req-build-59y8nu38/third_party/utf8 -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/include/python3.6m -c ctcdecode/src/scorer.cpp -o build/temp.macosx-10.7-x86_64-3.6/ctcdecode/src/scorer.o -O3 -DKENLM_MAX_ORDER=6 -std=c++11 -fPIC -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB -DINCLUDE_KENLM -DKENLM_MAX_ORDER=6 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ctc_decode -D_GLIBCXX_USE_CXX11_ABI=0
    warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]warning
    : include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    ctcdecode/src/binding.cpp:1:10: fatal error: 'algorithm' file not found
    In file included from ctcdecode/src/path_trie.cpp:1:
    ctcdecode/src/path_trie.h:4:10: #include <algorithm>fatal error: 'algorithm' file not found
             ^~~~~~~~~~~
    
    #include <algorithm>
             ^~~~~~~~~~~
    warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    In file included from ctcdecode/src/decoder_utils.cpp:1:
    ctcdecode/src/decoder_utils.h:4:10: fatal error: 'utility' file not found
    #include <utility>
             ^~~~~~~~~
    In file included from ctcdecode/src/scorer.cpp:1:
    ctcdecode/src/scorer.h:4:10: fatal error: 'memory' file not found
    #include <memory>
             ^~~~~~~~
    1 warning and 1 error generated.
    1 warning and 1 error generated.
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/envs/masr/include -arch x86_64 -I/anaconda3/envs/masr/include -arch x86_64 -I/private/tmp/pip-req-build-59y8nu38/third_party/kenlm -I/private/tmp/pip-req-build-59y8nu38/third_party/openfst-1.6.7/src/include -I/private/tmp/pip-req-build-59y8nu38/third_party/ThreadPool -I/private/tmp/pip-req-build-59y8nu38/third_party/boost_1_67_0 -I/private/tmp/pip-req-build-59y8nu38/third_party/utf8 -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/TH -I/anaconda3/envs/masr/lib/python3.6/site-packages/torch/lib/include/THC -I/anaconda3/envs/masr/include/python3.6m -c ctcdecode/src/ctc_beam_search_decoder.cpp -o build/temp.macosx-10.7-x86_64-3.6/ctcdecode/src/ctc_beam_search_decoder.o -O3 -DKENLM_MAX_ORDER=6 -std=c++11 -fPIC -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB -DINCLUDE_KENLM -DKENLM_MAX_ORDER=6 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ctc_decode -D_GLIBCXX_USE_CXX11_ABI=0
    error: command 'gcc' failed with exit status 1
    warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    In file included from ctcdecode/src/ctc_beam_search_decoder.cpp:1:
    ctcdecode/src/ctc_beam_search_decoder.h:4:10: fatal error: 'string' file not found
    #include <string>
             ^~~~~~~~
    1 warning and 1 error generated.
    1 warning and 1 error generated.
    1 warning and 1 error generated.
    ----------------------------------------
ERROR: Command "/anaconda3/envs/masr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-req-build-59y8nu38/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-7w9xl5so/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-req-build-59y8nu38/

**Comment by LnFen** [comment]
git clone --recursive https://github.com/parlance/ctcdecode.git 
这样克隆项目,再运行试一试

**Comment by gs5264** [comment]
> git clone --recursive https://github.com/parlance/ctcdecode.git
> 这样克隆项目,再运行试一试

您好，您给的这个就是作者项目里面给的，没有区别，就是这样会报错
