### ISSUE TITLE
模型预测时间慢

### ISSUE THREAD

**Issue by tai960519073** [lukhy/masr#3]
你好，非常感谢你的项目。有个问题向你请教下，加上语言模型以后精度确实提高不少，不过预测速度也慢了好多，预测示例语音需要将近10秒。请问怎样缩短预测时间呢？

**Comment by lukhy** [comment]
哇，很高兴看到你把语言模型环境配置成功了！我的环境都是配置在服务器上的，还没有在本地测试过。

10秒确实太慢了一些，可以让我看一下你的运行效果截图吗？

然后，你的CPU是多少核心多少线程的？

**Comment by tai960519073** [comment]
> 哇，很高兴看到你把语言模型环境配置成功了！我的环境都是配置在服务器上的，还没有在本地测试过。
> 
> 10秒确实太慢了一些，可以让我看一下你的运行效果截图吗？
> 
> 然后，你的CPU是多少核心多少线程的？

非常感谢你的回复，问题解决了，现在预测示例语音3s之内，。我会长期关注咱们的项目，感谢你的分享

**Comment by lukhy** [comment]
哈哈，感谢关注～
不过我还是很好奇你是怎么解决的？

**Comment by tai960519073** [comment]
> 哈哈，感谢关注～
> 不过我还是很好奇你是怎么解决的？

我部署的有问题，不是咱们模型问题

**Comment by WiliiamBryant** [comment]
> 你好，非常感谢你的项目。有个问题向你请教下，加上语言模型以后精度确实提高不少，不过预测速度也慢了好多，预测示例语音需要将近10秒。请问怎样缩短预测时间呢？

你好，请问你在配置环境时有没有改过ctcdecode工具里面的代码呢？我这里使用语言模型一直报Segmentation fault，找遍各种方法都没解决，如果你有办法麻烦回复我一下，万分感谢

**Comment by feifaxiaoming** [comment]
centos带不起来
