### ISSUE TITLE
import ctcdecode 报错

### ISSUE THREAD

**Issue by whocareblablabla** [lukhy/masr#4]
成功安装，但是老是报错
File "tests/test.py", line 8, in <module>
    import ctcdecode
  File "/Users/wang/Desktop/partime/venv/lib/python3.6/site-packages/ctcdecode/__init__.py", line 1, in <module>
    from ._ext import ctc_decode
ImportError: dlopen(/Users/wang/Desktop/partime/venv/lib/python3.6/site-packages/ctcdecode/_ext/ctc_decode.cpython-36m-darwin.so, 2): Symbol not found: __ZN3c105ErrorC1ENS_14SourceLocationERKSs
  Referenced from: /Users/wang/Desktop/partime/venv/lib/python3.6/site-packages/ctcdecode/_ext/ctc_decode.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/wang/Desktop/partime/venv/lib/python3.6/site-packages/ctcdecode/_ext/ctc_decode.cpython-36m-darwin.so

**Comment by lukhy** [comment]
你好，在`import ctcdecode` 之前必须先`import torch` 。这样是否解决了你的问题？

**Comment by whocareblablabla** [comment]
还是没有解决。
我在 ctcdecode 的 issue 里看到了两种解决方法
一种是你说的先 import torch，不行。
另一种是查看 anaconda ，但我是创建虚拟环境 venv，在里面配置的，方法也不适用

**Comment by tai960519073** [comment]
> 还是没有解决。
> 我在 ctcdecode 的 issue 里看到了两种解决方法
> 一种是你说的先 import torch，不行。
> 另一种是查看 anaconda ，但我是创建虚拟环境 venv，在里面配置的，方法也不适用
你可以尝试下使用conda创建环境

**Comment by lukhy** [comment]
你好，谢谢你的反馈，requirements.txt已更新。
你大概用的是最新版的torch1.1，ctcdecode那个包目前不支持最新版的torch1.1。
在venv虚拟环境下降级pytorch可以解决这个问题。
```
pip install torch==1.0.1
```

**Comment by tai960519073** [comment]
> 你好，谢谢你的反馈，requirements.txt已更新。
> 你大概用的是最新版的torch1.1，ctcdecode那个包目前不支持最新版的torch1.1。
> 在venv虚拟环境下降级pytorch可以解决这个问题。
> 
> ```
> pip install torch==1.0.1
> ```


> 你好，谢谢你的反馈，requirements.txt已更新。
> 你大概用的是最新版的torch1.1，ctcdecode那个包目前不支持最新版的torch1.1。
> 在venv虚拟环境下降级pytorch可以解决这个问题。
> 
> ```
> pip install torch==1.0.1
> ```

我的电脑是mac，torch也是1.1的，可以安装ctcdecode。不过由于mac高版本系统的关系，C文件编译的时候需要修改下

**Comment by lukhy** [comment]
怎么修改？

**Comment by tai960519073** [comment]
mac os 不再支持libstdc++，需要改成libc++

**Comment by WiliiamBryant** [comment]
> 你好，谢谢你的反馈，requirements.txt已更新。
> 你大概用的是最新版的torch1.1，ctcdecode那个包目前不支持最新版的torch1.1。
> 在venv虚拟环境下降级pytorch可以解决这个问题。
> 
> ```
> pip install torch==1.0.1
> ```

你好，我改成了1.0.1版本，还是报和楼主一样的问题
ImportError: dlopen(/Users/wang/Desktop/partime/venv/lib/python3.6/site-packages/ctcdecode/_ext/ctc_decode.cpython-36m-darwin.so, 2): Symbol not found: __ZN3c105ErrorC1ENS_14SourceLocationERKSs
找了下解决方法说是编译环境的问题，请问masr项目和deep speech2一样只支持python2.7是吗，还是其他原因

**Comment by lukhy** [comment]
我用的python3

**Comment by chen849157649** [comment]
> 还是没有解决。
> 我在 ctcdecode 的 issue 里看到了两种解决方法
> 一种是你说的先 import torch，不行。
> 另一种是查看 anaconda ，但我是创建虚拟环境 venv，在里面配置的，方法也不适用

@whocareblablabla 你好，这个问题你解决了吗？anaconda下的Python3, 和服务器自带Python3下，且torch==1.0.1下安装编译成功，但是导入还是报一样的错，你是怎么解决的？多谢了
