### ISSUE TITLE
【问题请教】大佬您实现这一套系统花了多久啊

### ISSUE THREAD

**Issue by zyzisyz** [lukhy/masr#6]
hi，我是一名语音识别初学者小白，无意间看到了你的这个高质量的repo。
想请教一下您实现这个系统花了多久？

如果我想从零开始自己实现一个可用的个人语音识别系统，请问一下您有什么论文、教程、博客和书籍可以推荐吗？

谢谢~~~

**Comment by lukhy** [comment]
>我想从零开始自己实现一个可用的个人语音识别系统，请问一下您有什么论文、教程、博客和书籍可以推荐吗？

推荐论文：

循环+Attention：https://arxiv.org/abs/1508.01211

2d卷积+循环：https://arxiv.org/abs/1512.02595

1d卷积：https://arxiv.org/abs/1609.03193

1d卷积+GLU：https://arxiv.org/abs/1712.09444（本项目类似于这篇，不过小很多）

**Comment by zyzisyz** [comment]
好的，谢谢你的回复
